#pragma once
#ifndef FRAMEWORK_H_
#define FRAMEWORK_H_
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <Windows.h>
#include <ShlObj.h>
#include <TlHelp32.h>
#include <atlconv.h>
#include <iphlpapi.h>
#include <malloc.h>
#include <mmsystem.h>
#include <psapi.h>
#include <shellapi.h>
#include <stdio.h>
#include <tchar.h>
#include <math.h>
#include <stdlib.h>

#include <atomic>
#include <algorithm>
#include <array>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <execution>
#include <filesystem>
#include <iostream>
#include <limits>
#include <memory>
#include <fstream>
#include <sstream>
#include <string>
#include <thread>
#include <unordered_map>
#include <vector>
#include <random>
#include <utility>
#endif  // FRAMEWORK_H_