name: Windows

on: [push, pull_request]

permissions:
  contents: read

jobs:
  msbuild:
    runs-on: windows-2022
    strategy:
      matrix:
        toolset: [ClangCL, MSVC]
        configuration: [Debug, Ring0, Ring3]
    steps:
    - uses: actions/checkout@v4
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: Set toolset
      if: matrix.toolset == 'ClangCL'
      run: echo "toolset=/p:PlatformToolset=${{ matrix.toolset }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: Build
      shell: cmd
      run: msbuild Samidare.sln /p:Platform=x64 /p:Configuration=${{ matrix.configuration }} ${{ env.toolset }}
